package Ch_4;

public class four_2 {

	
	/*STRAIGHT FORWARD BFS IMPLEMENTAION.
	 * EITHER SOLVE IT RECURSIVELY OT ITERATIVELY DOESNT MATTER.
	 * DO IT ON YOUR OWN. WOULD NOT BE A DIFFICULT TASK AT ALL.
	 */
	
}
